### ISSUE TITLE
set-up empty function for time series plot

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/ggexpress#4]
Set-up empty functions (with appropriate function names) containing no code in the files where you will eventually write code. Write function documentation (e.g., complete docstrings). These are the functions you wrote about in your proposal.

- This function deals with time series data.
- It turns a `csv` file into a time series file, and make decomposition plots, which includes 4 subplots: raw data, estimated trend component, estimated seasonal/cyclic component and estimated remainder component.

**Comment by zouwenjiao** [comment]
- [x] create the function

- [x] write docs
