### ISSUE TITLE
ts_plot bug fix

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/ggexpress#56]
- using a function called `time` but do not use the double colon notation. Does this function come from a package? Has the package been declared as a dependency?

- double colon notation not used on the `ts` function. Was the package for this function declared as a dependency?

**Comment by zouwenjiao** [comment]
- Have removed `time` function

**Comment by zouwenjiao** [comment]
- `ts` is from `stats` package.  Have added double colon notation to it.
